//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecSMS.Maui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecSMS.Maui.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth device selection was canceled..
        /// </summary>
        internal static string BluetoothCancelled {
            get {
                return ResourceManager.GetString("BluetoothCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard..
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy OTP.
        /// </summary>
        internal static string CopyOtp {
            get {
                return ResourceManager.GetString("CopyOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted OTP sent to desktop..
        /// </summary>
        internal static string EncryptedOtpSent {
            get {
                return ResourceManager.GetString("EncryptedOtpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website exposing corruption.
        /// </summary>
        internal static string Link1Title {
            get {
                return ResourceManager.GetString("Link1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Passwoord Manager PWA.
        /// </summary>
        internal static string Link2Title {
            get {
                return ResourceManager.GetString("Link2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Generative AI based internal search engine for your own website.
        /// </summary>
        internal static string Link3Title {
            get {
                return ResourceManager.GetString("Link3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External links (open in your browser):.
        /// </summary>
        internal static string LinksIntro {
            get {
                return ResourceManager.GetString("LinksIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Detail.
        /// </summary>
        internal static string MessageDetailTitle {
            get {
                return ResourceManager.GetString("MessageDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages.
        /// </summary>
        internal static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to copy..
        /// </summary>
        internal static string NothingToCopy {
            get {
                return ResourceManager.GetString("NothingToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to send..
        /// </summary>
        internal static string NothingToSend {
            get {
                return ResourceManager.GetString("NothingToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL found..
        /// </summary>
        internal static string NoUrlFound {
            get {
                return ResourceManager.GetString("NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        internal static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission required to read SMS..
        /// </summary>
        internal static string PermissionRequired {
            get {
                return ResourceManager.GetString("PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Windows client.
        /// </summary>
        internal static string SendToWindows {
            get {
                return ResourceManager.GetString("SendToWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string TabLinks {
            get {
                return ResourceManager.GetString("TabLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string TabMessages {
            get {
                return ResourceManager.GetString("TabMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open link..
        /// </summary>
        internal static string UnableToOpenLink {
            get {
                return ResourceManager.GetString("UnableToOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected. Waiting for PQ key bundle from Windows....
        /// </summary>
        internal static string WaitingForPqBundle {
            get {
                return ResourceManager.GetString("WaitingForPqBundle", resourceCulture);
            }
        }
    }
}
